shooting_with_camera : ['nikon', 'olympus']
shooting_with_lens : ['35mm', '50mm', '85mm']
shooting_with_filter : ['none', 'polarizer', 'uv']

available_options :
    - 
        - nikon
        - olympus'
        - fuji

    -
        - 20mm
        - 35mm
        - 50mm
        - 85mm

    -
        - none
        - polarizer
        - uv
        - haze
        - closeup
